### ISSUE TITLE
对Lifetime Assignment2答案的疑惑

### ISSUE THREAD

**Issue by SwingURM** [Extra-Creativity/Modern-Cpp-Basics#2]
https://github.com/Extra-Creativity/Modern-Cpp-Basics/blob/cda48321872382a5ce67b505fa2e1fb7a45898ed/05-Lifetime%20%26%20Type%20Safety/Answer.md?plain=1#L19
https://github.com/Extra-Creativity/Modern-Cpp-Basics/blob/cda48321872382a5ce67b505fa2e1fb7a45898ed/05-Lifetime%20%26%20Type%20Safety/Answer.md?plain=1#L33-L34
https://github.com/Extra-Creativity/Modern-Cpp-Basics/blob/cda48321872382a5ce67b505fa2e1fb7a45898ed/05-Lifetime%20%26%20Type%20Safety/Answer.md?plain=1#L39-L40
问题：为什么允许使用返回指向局部变量的引用

我注意到https://www.learncpp.com/cpp-tutorial/return-by-reference-and-return-by-address/ 中似乎描述了类似的问题，但认为是ub

> Also note that if a program returns a dangling reference, the reference is left dangling before the copy is made, which will lead to undefined behavior:

```cpp
#include <iostream>
#include <string>

const std::string& getProgramName() // will return a const reference
{
    const std::string programName{ "Calculator" };

    return programName;
}

int main()
{
    std::string name { getProgramName() }; // makes a copy of a dangling reference
    std::cout << "This program is named " << name << '\n'; // undefined behavior

    return 0;
}
```

我构造如下代码进行测试
```cpp
#include <vector>

// UB, vec是临时变量，悬垂引用
std::vector<int> const& Func1(std::vector<int> vec) {
  return vec;
}

int main() {
  std::vector<int> a = {4, 5, 6};

  auto c1 = Func1(a);  // ok, because auto deduces std::vector
  // which copies and makes a new variable.

  return 0;
}
```
以上代码中，Func1触发了-Wreturn-local-addr
我在windows msys2 clang++中能顺利编译并运行这段代码，在g++中能编译但运行失败，直接触发Exception 0xc0000005 encountered at address 0x7ff7931d2a9c: Access violation reading location 0x00000008

另外感谢您无私提供这么现代的教程^_^

**Comment by Extra-Creativity** [comment]
a96b9ab 已解决，你说的很对
